
POST http://127.0.0.1:8000/api/login
Content-type: application/json
Accept: application/json

{ 
  "username": "jorge4",
  "password": "1234",
  "remember": true
}

###
POST http://127.0.0.1:8000/api/register
Content-type: application/json
Accept: application/json

{
  "username": "jorge5",
  "password": 1234,
  "password_confirmation": 1234
}

###
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: 2|aQRIn2V08xeZ8tRMhh8qG2s6V7mqWYlURwTs2Qpx84422874

###
GET http://127.0.0.1:8000/api/users
Authorization:Bearer 2|oyiOu8jkzTd2HUFKLFd6s4aBEZXLccoRr7eHrpiy4475ced1
Accept: application/json

###
POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization:Bearer 23|IO8jYkD85GHr94NUmRDPkZwSo8r3HtanZulA8myYb928dc65

###
POST http://127.0.0.1:8000/api/inmueble
Authorization:Bearer 2|oyiOu8jkzTd2HUFKLFd6s4aBEZXLccoRr7eHrpiy4475ced1
Content-Type: application/json
Accept: application/json

{
  "referencia": 123213214,
  "ubicacion": "Calle de la Rosa, 12",
  "tamano": 100,
  "habitaciones": 4,
  "garaje": true,
  "trastero": false,
  "fechaBajaAnuncio": "2021-06-01",
  "precio": 100000,
  "fechaRegistro": "2021-10-05"
}


###