
POST http://127.0.0.1:8000/api/login
Content-type: application/json
Accept: application/json

{ 
  "username": "jorge2s",
  "password": "1234",
  "remember": true
}

###
POST http://127.0.0.1:8000/api/register
Content-type: application/json
Accept: application/json

{
  "username": "jorge2s",
  "password": 1234,
  "password_confirmation": 1234
}

###
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer 73|18A2TE8v4YhZSccivTtOwcBj1i8bVMLlt06P0kbR99142a57

###
GET http://127.0.0.1:8000/api/users
Authorization:Bearer 2|oyiOu8jkzTd2HUFKLFd6s4aBEZXLccoRr7eHrpiy4475ced1
Accept: application/json

###
POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 71|YHc9xmb3F6BCXzIsk9t2dODE1ATAq3lKvS0blFHH824ee27

###
POST http://127.0.0.1:8000/api/inmueble
Authorization:Bearer 83|riX3uphYfI2su1Uqc8gwcXCZzPZc9Gwup8cYTJeGb68bd413
Content-Type: application/json
Accept: application/json

{
  "referencia": 123221441,
  "ubicacion": "Calle Pascual, 12",
  "tamano": 120,
  "habitaciones": 4,
  "garaje": true,
  "trastero": false,
  "fechaBajaAnuncio": "2021-06-01",
  "precio": 100000,
  "fechaRegistro": "2021-10-05"
}


###