# POST INMUEBLE
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "jorge",
    "password": "1234"
}
###
POST http://127.0.0.1:8000/api/inmueble
Authorization: Bearer 22|anqjU9K0kSWThMljmcAyFuVhXcLpOPadeMsjavgj98b59441 
Content-Type: application/json

{
  "referencia": 12421412421,
  "ubicacion": "Casa de campo",
  "descripcion": "Casa de campo en la montaña",
  "precio": 100000,
  "tipo": "Casa",
  "direccion": "Calle 1",
  "ciudad": "Cuenca",
  "provincia": "Azuay",
  "pais": "Ecuador",
  "imagen": "https://www.google.com",
  "estado": "Disponible",
  "usuario": 1
}